//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelodyShop.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataToOrder
    {
        public int id { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public string email { get; set; }
        public string phoneNumber { get; set; }
        public string street { get; set; }
        public string hoseNumber { get; set; }
        public string postalCode { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string messageToOrder { get; set; }
        public int cartId { get; set; }
    
        public virtual Cart Cart { get; set; }
    }
}
