//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MelodyShop.DataAccessLayer
{
  using System;
  using System.Collections.Generic;
  using System.ComponentModel.DataAnnotations;

  public partial class Product
  {
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Product()
    {
      this.Carts = new HashSet<Cart>();
    }

    public int id { get; set; }

    [Display(Name = "Producent")]
    public string producer { get; set; }

    [Display(Name = "Model")]
    public string model { get; set; }

    [Display(Name = "Szczegóły")]
    public string detail { get; set; }

    [Display(Name = "Cena")]
    public decimal price { get; set; }

    public int categoryId { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<Cart> Carts { get; set; }
    public virtual Category Category { get; set; }
  }
}
